unstable_features = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
use_small_heuristics = "Max"
max_width = 120
single_line_if_else_max_width = 120
single_line_let_else_max_width = 120
struct_lit_single_line = true
struct_lit_width = 120
struct_variant_width = 120
array_width = 120
chain_width = 120
fn_call_width = 120
comment_width = 120
binop_separator = "Back"
empty_item_single_line = false
hex_literal_case = "Upper"
match_block_trailing_comma = true
merge_derives = true
imports_granularity="Crate"
normalize_comments = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
trailing_comma = "Never"
trailing_semicolon = true
use_try_shorthand = true
